#!/usr/bin/env bash
# Installs and configures Nginx web server

apt-get update -y
apt-get install -y nginx

echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html

# Alternative restart methods if service doesn't work:
/etc/init.d/nginx restart
# or
nginx -s reload

